version: '3.1'
services:
  redis:
    image: redis:5.0.7-alpine
    container_name: 'redis-container'
    command: redis-server --requirepass $REDIS_PASSWORD
    volumes:
      - ./redis-data:/data
  mongodb:
    image: mongo:4.2.3
    container_name: 'mongo-container'
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
  publish-places:
    build: .
    links:
      - redis
    command: python publish-places.py
    container_name: 'publish-places-container'
    restart: unless-stopped
    depends_on:
      - redis
      - subscribe-places
    environment:
      GOOGLE_KEY: $GOOGLE_KEY
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_HOST: $REDIS_HOST
      TEXT_SEARCH_TIMING: $TEXT_SEARCH_TIMING
      PYTHONPATH: $PYTHONPATH
      PYTHON_LOG: $PYTHON_LOG
    volumes:
      - .:/usr/src
  subscribe-places:
    build: .
    command: python subscribe-info.py
    container_name: 'subscribe-places-container'
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    environment:
      GOOGLE_KEY: $GOOGLE_KEY
      REDIS_PASSWORD: $REDIS_PASSWORD
      REDIS_HOST: $REDIS_HOST
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_HOST: $MONGO_INITDB_HOST
      PLACES_ID_TIMING: $PLACES_ID_TIMING
      PYTHONPATH: $PYTHONPATH
      PYTHON_LOG: $PYTHON_LOG
    links:
      - mongodb
      - redis
    volumes:
      - .:/usr/src