version: '3.1'
services:
  mongodb:
    image: mongo:4.2.3
    container_name: 'mongo-container'
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db
  python:
    build: ./python
    command: bash -c "sleep 100000000000000 && python /usr/src/MongoClient.py"
    container_name: 'python-project'
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_INITDB_DATABASE: $MONGO_INITDB_DATABASE
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
      MONGO_INITDB_HOST: $MONGO_INITDB_HOST
      GOOGLE_KEY: $GOOGLE_KEY
      PYTHONPATH: $PYTHONPATH
    links:
      - mongodb
    volumes:
      - ./python:/usr/src