# Generated by Django 2.2.11 on 2020-03-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField()),
                ('name', models.CharField(max_length=150, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('international_phone_number', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=300, null=True)),
                ('place_id', models.CharField(max_length=150)),
                ('web_status', models.CharField(max_length=150)),
            ],
        ),
    ]
