# Generated by Django 2.2.11 on 2020-03-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
