# Generated by Django 2.2.11 on 2020-03-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_info', '0003_auto_20200312_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='website',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
