# Generated by Django 2.2.11 on 2020-03-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place_info', '0004_auto_20200313_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeinfo',
            name='website',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
